name: 🚀 Deploy to VPS

on:
  push:
    branches:
      - master  # or your branch

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Connect and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/toufi/ai-telegram-assistant
            git pull origin master
            sudo systemctl restart ai-telegram-bot
            
